# Generated by Django 5.0.7 on 2024-07-27 19:56

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('UserManagement', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Flight',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('flight_id', models.CharField(blank=True, max_length=255, null=True)),
                ('airline', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_city', models.CharField(blank=True, max_length=255, null=True)),
                ('arrival_city', models.CharField(blank=True, max_length=255, null=True)),
                ('departure_schedule', models.DateTimeField(blank=True, null=True)),
                ('arrival_schedule', models.DateTimeField(blank=True, null=True)),
                ('flight_duration', models.CharField(blank=True, max_length=255, null=True)),
                ('seats_available', models.JSONField()),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.status')),
            ],
            options={
                'db_table': 'flight_table',
            },
        ),
        migrations.CreateModel(
            name='FlightSchedule',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(null=True)),
                ('id', models.UUIDField(default=uuid.UUID, editable=False, primary_key=True, serialize=False)),
                ('seat_number', models.CharField(blank=True, max_length=255, null=True)),
                ('flight_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='flight_details', to='Flights.flight')),
                ('status', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='UserManagement.status')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_details', to='UserManagement.user')),
            ],
            options={
                'db_table': 'flight_schedule',
            },
        ),
    ]
